### PR TITLE
Adopt to new get_info_table_raw_csv API

### PR DESCRIPTION
**Pull request by jspricke**

### CODE REVIEW

**Comment by jspricke** [comment]
This was changed in wstool in 2016: https://github.com/vcstools/wstool/pull/93
Also, would be great to have a new release here.

**Comment by jspricke** [comment]
Relevant bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=894699

I wonder why this didn't show up on any build farm before ;).

**Comment by wjwwood** [comment]
I don't know why that test has not been running (or is running and doesn't fail)...

🔥Also the tests are currently broken due to new upstream checks in setuptools or something.🔥 

I'm not sure when I'll get to this.

**Comment by wjwwood** [comment]
I put the "help wanted" label here, only because I could use help fixing the CI (does not look trivial off-hand). If no one has time, I'll get to it eventually.

**Comment by tkruse** [comment]
So we do have a test that fails: test_info_only. Travis CI build currently fails when it tries to install the wstool dependency for `python setup.py install`:

```
Searching for wstool>=0.1.12
Reading https://pypi.python.org/simple/wstool/
Downloading https://pypi.python.org/packages/66/7b/a3e4195605644e54658101acc13593703bde9fb67731e4565ac225a5bdb5/wstool-0.1.17.tar.gz#md5=656e6456e31dc5a43f0a9aae9efed7ea
Best match: wstool 0.1.17
Processing wstool-0.1.17.tar.gz
Writing /tmp/easy_install-3ms7zcbm/wstool-0.1.17/setup.cfg
Running wstool-0.1.17/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3ms7zcbm/wstool-0.1.17/egg-dist-tmp-78xade9f
error: Setup script exited with error: SandboxViolation: mkdir('/home/travis/virtualenv/python3.4.6/etc', 511) {}
```

I can reproduce locally when creating a fresh virtualenv and running `python setup.py install`.
Note that manually downloading the wstool tar from pypi and locally running `python setup.py -q bdist_egg` works as expected, including succesful creation of the `etc` folder. So it's only within the context of running python setup.py install of rosinstall that there is a sandbox violation for executing wstools/setup.py.


**So a workaround could be to first run `pip install wstool` separately in travis, then rosinstalls setup.py.**. I will create a PR for that.

The only similar issue I found so far was this, but not helpful for me.
https://github.com/ansible/ansible/issues/1840


### As to why this did not fail on the buildfarm (or travis) earlier:

At least on travis, I can see that the wstool dependency used was 1.1.13: https://travis-ci.org/vcstools/rosinstall/jobs/325577980

```
Searching for wstool>=0.1.12
Reading https://pypi.python.org/simple/wstool/
...
Best match: wstool 0.1.13
```

Why that 0.1.13 is chosen as best match and not the latest I don't know. In any case this PR should update the dependency to at least 0.1.14 where the change in the API was done. Also given this was an API change, one could argue the minor versions should have been increased in wstool, but it's an easy oversight to miss that wstool is at the same time a CLI tool and a library to rosinstall.

**Comment by jspricke** [comment]
Thanks Thibault!
Closing this in favor of #117

**Pull request closed without merging**
