### PR TITLE
Add fake identity for VCSs

### PR DESCRIPTION
**Pull request by jspricke**
This makes the unit tests self contained.

### CODE REVIEW

**Comment by wjwwood** [comment]
@jspricke I pruned the list of Python versions (no longer supported) and that should address one of the CI setup problems. But it looks like git is failing in many of the tests with the "Tell me who you are" error.

**Comment by jspricke** [comment]
Same as for wstool, all tests results are gone.

**Comment by wjwwood** [comment]
Ok, I finally got the tests running again. I think the remaining failures are related to your changes. If you like I can take my changes to get the tests working and put them on a separate pr.

But either way, please have a look at the remaining failures.

**Comment by jspricke** [comment]
Fixed. Thanks for working on the Travis part.

**Comment by wjwwood** [comment]
@jspricke I believe it is working here, because the tests are laid out in a more conventional way (everything in files starting with `test_` in the folder `test`).

**Comment by wjwwood** [comment]
Oops, posted the comment on the wrong issue...

**Pull request merged**
